---
title: "Progress"
author: "Peter Sykora"
date: "11/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library("gridExtra")   
```

```{r}

students <- read_csv("../data/student-mat.csv")
head(students)

```

```{r}

students_modified <- students %>%
  select(schoolsup, famsup, paid, activities, nursery, Dalc, Walc)
head(students_modified)

```

```{r}

# look at the boxplots of `Dalc` and `Walc` vs. `schoolsup`
p1 <- ggplot(students_modified, aes(x = schoolsup, y = Dalc)) +
  geom_boxplot()
p2 <- ggplot(students_modified, aes(x = schoolsup, y = Walc)) +
  geom_boxplot()
grid.arrange(p1, p2, ncol = 2)

```

```{r}

# look at the histograms of `Dalc` and `Walc` vs. `schoolsup`
p1 <- ggplot(students_modified, aes(x = Dalc)) +
  geom_bar(aes(fill = schoolsup), position="dodge2")
p2 <- ggplot(students_modified, aes(x = Walc)) +
  geom_bar(aes(fill = schoolsup), position="dodge2")
grid.arrange(p1, p2, ncol = 2)


```

```{r}

# look at the boxplots of `Dalc` and `Walc` vs. `famsup`
p1 <- ggplot(students_modified, aes(x = famsup, y = Dalc)) +
  geom_boxplot()
p2 <- ggplot(students_modified, aes(x = famsup, y = Walc)) +
  geom_boxplot()
grid.arrange(p1, p2, ncol = 2)

```

```{r}

# look at the histograms of `Dalc` and `Walc` vs. `famsup`
p1 <- ggplot(students_modified, aes(x = Dalc)) +
  geom_bar(aes(fill = famsup), position="dodge2")
p2 <- ggplot(students_modified, aes(x = Walc)) +
  geom_bar(aes(fill = famsup), position="dodge2")
grid.arrange(p1, p2, ncol = 2)

```


```{r}

# look at the boxplots of `Dalc` and `Walc` vs. `paid`
p1 <- ggplot(students_modified, aes(x = paid, y = Dalc)) +
  geom_boxplot()
p2 <- ggplot(students_modified, aes(x = paid, y = Walc)) +
  geom_boxplot()
grid.arrange(p1, p2, ncol = 2)

```

```{r}

# look at the histograms of `Dalc` and `Walc` vs. `paid`
p1 <- ggplot(students_modified, aes(x = Dalc)) +
  geom_bar(aes(fill = paid), position="dodge2")
p2 <- ggplot(students_modified, aes(x = Walc)) +
  geom_bar(aes(fill = paid), position="dodge2")
grid.arrange(p1, p2, ncol = 2)

```


```{r}

# look at the boxplots of `Dalc` and `Walc` vs. `activities`
p1 <- ggplot(students_modified, aes(x = activities, y = Dalc)) +
  geom_boxplot()
p2 <- ggplot(students_modified, aes(x = activities, y = Walc)) +
  geom_boxplot()
grid.arrange(p1, p2, ncol = 2)

```

```{r}

# look at the histograms of `Dalc` and `Walc` vs. `activities`
p1 <- ggplot(students_modified, aes(x = Dalc)) +
  geom_bar(aes(fill = activities), position="dodge2")
p2 <- ggplot(students_modified, aes(x = Walc)) +
  geom_bar(aes(fill = activities), position="dodge2")
grid.arrange(p1, p2, ncol = 2)

```


```{r}

# look at the boxplots of `Dalc` and `Walc` vs. `nursery`
p1 <- ggplot(students_modified, aes(x = nursery, y = Dalc)) +
  geom_boxplot()
p2 <- ggplot(students_modified, aes(x = nursery, y = Walc)) +
  geom_boxplot()
grid.arrange(p1, p2, ncol = 2)

```

```{r}

# look at the histograms of `Dalc` and `Walc` vs. `nursery`
p1 <- ggplot(students_modified, aes(x = Dalc)) +
  geom_bar(aes(fill = nursery), position="dodge2")
p2 <- ggplot(students_modified, aes(x = Walc)) +
  geom_bar(aes(fill = nursery), position="dodge2")
grid.arrange(p1, p2, ncol = 2)

```


