---
title: "Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
```

```{r}
math <- read.csv('student-matcsv.csv')
math
```
```{r}
table(math$goout)
ggplot(math, mapping=aes(x=Dalc)) +
  geom_bar(aes(fill=as.factor(goout)),position="dodge2")

ggplot(math, mapping=aes(x=Walc)) +
  geom_bar(aes(fill=as.factor(goout)),position="dodge2")

cor(math$goout, math$Walc)
# 0.42 positive correlation, the more they go out, the more they drink during weekends

cor(math$goout, math$Dalc)
# 0.27 positive correlation, the more they go out, the more they drink during weekdays
```

```{r}
#5 is very good health, 1 is bad health
table(math$health)
ggplot(math, mapping=aes(x=Dalc)) +
  geom_bar(aes(fill=as.factor(health)),position="dodge2")

ggplot(math, mapping=aes(x=Walc)) +
  geom_bar(aes(fill=as.factor(health)),position="dodge2")


cor(math$health, math$Walc)
#Little to no correlation, but still positive

cor(math$health, math$Dalc)
#Little to no correlation, but still positive
```

```{r}
math %>% 
  select(Walc, Dalc, absences) 

table(math$absences)
```

```{r}
#1 - <2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, or 4 - >10 hours)
math %>% 
  select(Walc, Dalc, studytime)
ggplot(math, mapping=aes(x=Dalc)) +
  geom_bar(aes(fill=as.factor(studytime)),position="dodge2")

ggplot(math, mapping=aes(x=Walc)) +
  geom_bar(aes(fill=as.factor(studytime)),position="dodge2")


cor(math$studytime, math$Walc)
cor(math$studytime, math$Dalc)
#More they drink, less they study
```
```{r}
#numeric: n if 1<=n<3, else 4)
math %>% 
  select(Walc, Dalc, failures)
ggplot(math, mapping=aes(x=Dalc)) +
  geom_bar(aes(fill=as.factor(failures)),position="dodge2")

ggplot(math, mapping=aes(x=Walc)) +
  geom_bar(aes(fill=as.factor(failures)),position="dodge2")


cor(math$failures, math$Walc)
cor(math$failures, math$Dalc)
#More they drink, more number of failures
```

